//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("NMultiTool provides commands useful during build or install of an application or " +
    "library")]
[assembly: AssemblyCompany("github.trondr")]
[assembly: AssemblyProduct("NMultiTool")]
[assembly: AssemblyCopyright("Copyright © github.trondr 2016")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.16089.44.07433b1")]
[assembly: AssemblyVersion("1.0.16089.44")]
[assembly: AssemblyFileVersion("1.0.16089.44")]


